export const data = [
    {
      percentage: 43.1,
      year: 2024,
      thisYear: true,
      tableHeaders: [
        "Country",
        "Security Type",
        "Industry",
        "Invest Category",
        "Company",
        "Stock ticket",
        "Shares",
        "Avg Cost",
        "Last Price",
        "Dividends Collected",
        "Return",
        "Total Gain/Loss"
      ],
      tableRows: [
        {
          country: "Argentina",
          securityType: "Equity",
          industry: "Bank",
          investCategory: "Growth",
          company: "Banco Macro SA F Sponsor",
          stockTicket: 'BMA',
          shares: '35000',
          avgCost: '$48.55',
          lastPrice: '$82.62',
          dividendsCollected: '$0.00',
          return: '70.18%',
          total: '$2,891,700.00'
        },
        {
          country: "Argentina",
          securityType: "Equity",
          industry: "Bank",
          investCategory: "Growth",
          company: "Grupo Supervielle SA F Sponsor",
          stockTicket: 'SUPV',
          shares: '180000',
          avgCost: '$5.68',
          lastPrice: '$11.74',
          dividendsCollected: '$106,200.00',
          return: '117.08%',
          total: '$2,219,400.00'
        },
        {
          country: "Argentina",
          securityType: "Equity",
          industry: "Bank",
          investCategory: "Growth",
          company: "Grupo Financiero Galicia SA",
          stockTicket: 'GGAL',
          shares: '50000',
          avgCost: '$26.00',
          lastPrice: '$56.06',
          dividendsCollected: '$0.00',
          return: '115.62%',
          total: '$2,803,000.00'
        },
        {
          country: "Argentina",
          securityType: "Equity",
          industry: "Oil & Gas",
          investCategory: "Growth",
          company: "Pampa Energia SA F Sponsor",
          stockTicket: 'PAM',
          shares: '55000',
          avgCost: '$42.55',
          lastPrice: '$83.86',
          dividendsCollected: '$0.00',
          return: '97.09%',
          total: '$4,612,300.00'
        },
        {
          country: "Argentina",
          securityType: "Equity",
          industry: "Oil & Gas",
          investCategory: "Growth",
          company: "Visita Energy SAB de AD F",
          stockTicket: 'VIST',
          shares: '103000',
          avgCost: '$47.25',
          lastPrice: '$56.90',
          dividendsCollected: '$96,820.00',
          return: '22.41%',
          total: '$5,957,520.00'
        },
        {
          country: "Argentina",
          securityType: "Equity",
          industry: "Oil & Gas",
          investCategory: "Growth",
          company: "YPF S.A",
          stockTicket: 'YPF',
          shares: '55000',
          avgCost: '$15.79',
          lastPrice: '$39.57',
          dividendsCollected: '$0.00',
          return: '150.60%',
          total: '$2,176,350.00'
        },
        {
          country: "Argentina",
          securityType: "Bond",
          industry: "Fund",
          investCategory: "Dividend",
          company: "Bonos de la Republica Argentina",
          stockTicket: 'AL30',
          shares: '15000',
          avgCost: '$46.70',
          lastPrice: '$78.30',
          dividendsCollected: '$16,800.00',
          return: '70.06%',
          total: '$1,191,300.00'
        },
        {
          country: "Argentina",
          securityType: "Bond",
          industry: "Fund",
          investCategory: "Dividend",
          company: "B.E Globales $US Setp Up 2041",
          stockTicket: 'GD41',
          shares: '15000',
          avgCost: '$35.00',
          lastPrice: '$54.04',
          dividendsCollected: '$50,000.00',
          return: '63.92%',
          total: '$860,600.000'
        },
        {
          country: "Peru",
          securityType: "Equity",
          industry: "Bank",
          investCategory: "Value",
          company: "Credicorp LTD F Sponsor",
          stockTicket: 'BAP',
          shares: '9000',
          avgCost: '$165.61',
          lastPrice: '$197.03',
          dividendsCollected: '$22,456.00',
          return: '20.48%',
          total: '$1,795,726.00'
        },
        {
          country: "Spain",
          securityType: "Equity",
          industry: "Construction materials",
          investCategory: "Value",
          company: "Arcosa INC",
          stockTicket: 'ACA',
          shares: '30000',
          avgCost: '$76.02',
          lastPrice: '$111.96',
          dividendsCollected: '$12,349.00',
          return: '47.82%',
          total: '$3,371,149.00'
        },
        {
          country: "Brazil",
          securityType: "Equity",
          industry: "Construction materials",
          investCategory: "Value",
          company: "Gerdau",
          stockTicket: 'GGB',
          shares: '300000',
          avgCost: '$3.86',
          lastPrice: '$3.43',
          dividendsCollected: '$2,346.00',
          return: '-10.94%',
          total: '$1,031,346.00'
        },
        {
          country: "Italy",
          securityType: "Bond",
          industry: "Fund",
          investCategory: "Growth",
          company: "BTPS Aumundi 10 years",
          stockTicket: 'BTPS',
          shares: '52000',
          avgCost: '$98.28',
          lastPrice: '$104.52',
          dividendsCollected: '$88,984.00',
          return: '8.09%',
          total: '$5,524,024.00'
        },
        {
          country: "",
          securityType: "",
          industry: "",
          investCategory: "",
          company: "",
          stockTicket: '',
          shares: '',
          avgCost: '',
          lastPrice: '',
          dividendsCollected: '',
          return: 'Net Asset Value of Quantum Capital',
          total: '$39,703,562.50'
        },
      ],
    },
    {
      percentage: 38,
      year: 2023,
      thisYear: false,
      tableHeaders: [
        "Country",
        "Security Type",
        "Industry",
        "Invest Category",
        "Company",
        "Stock ticket",
        "Shares",
        "Avg Cost",
        "Last Price",
        "Dividends Collected",
        "Return",
        "Total Gain/Loss"
      ],
      tableRows: [
        {
          country: "US",
          securityType: "Bond",
          industry: "n/a",
          investCategory: "Dividend",
          company: "US Treasury 3 month bills",
          stockTicket: 'TBII',
          shares: '4000',
          avgCost: '$49.94',
          lastPrice: '$50.02',
          dividendsCollected: '$0.00',
          return: '0.16%',
          total: '$200,080.000'
        },
        {
          country: "Spain",
          securityType: "Equity",
          industry: "Energy",
          investCategory: "Value",
          company: "Iberdrola",
          stockTicket: 'IBE',
          shares: '38400',
          avgCost: '$8.73',
          lastPrice: '$11.05',
          dividendsCollected: '$22,656.00',
          return: '33.33%',
          total: '$446,976.000'
        },
        {
          country: "US",
          securityType: "Equity",
          industry: "Fund",
          investCategory: "Value",
          company: "Berkshire Hathway",
          stockTicket: 'BRKB',
          shares: '1000',
          avgCost: '$230.00',
          lastPrice: '$404.95',
          dividendsCollected: '$0.00',
          return: '76.07%',
          total: '$404,950.000'
        },
        {
          country: "Argentina",
          securityType: "Equity",
          industry: "Bank",
          investCategory: "Growth",
          company: "Grupo Financiero Galicia",
          stockTicket: 'GGAL',
          shares: '25000',
          avgCost: '$11.53',
          lastPrice: '$17.11',
          dividendsCollected: '$0.00',
          return: '48.40%',
          total: '$427,750.000'
        },
        {
          country: "US",
          securityType: "Equity",
          industry: "Tech",
          investCategory: "Growth",
          company: "Apple Inc",
          stockTicket: 'AAPL',
          shares: '1350',
          avgCost: '$126.30',
          lastPrice: '$175.84',
          dividendsCollected: '$1,269.00',
          return: '39.97%',
          total: '$238,653.000'
        },
        {
          country: "Argentina",
          securityType: "Equity",
          industry: "Oil & Gas",
          investCategory: "Growth",
          company: "YPF Sociedad S.A",
          stockTicket: 'YPF',
          shares: '12000',
          avgCost: '$10.88',
          lastPrice: '$17.47',
          dividendsCollected: '$0.00',
          return: '60.57%',
          total: '$209,640.000'
        },
        {
          country: "Brazil",
          securityType: "Equity",
          industry: "Oil & Gas",
          investCategory: "Dividend",
          company: "Petrolero Brasilero",
          stockTicket: 'PBR',
          shares: '12000',
          avgCost: '$11.66',
          lastPrice: '$15.97',
          dividendsCollected: '$13,440.00',
          return: '46.57%',
          total: '$205,080.000'
        },
        {
          country: "Peru",
          securityType: "Equity",
          industry: "Bank",
          investCategory: "Dividend",
          company: "Credicorp Ltd",
          stockTicket: 'BAP',
          shares: '750',
          avgCost: '$132.50',
          lastPrice: '$156.30',
          dividendsCollected: '$0.00',
          return: '17.96%',
          total: '$117,225.000'
        },
        {
          country: "Argentina",
          securityType: "Equity",
          industry: "Bank",
          investCategory: "Growth",
          company: "Banco Macro S.A",
          stockTicket: 'SAB.MC',
          shares: '3550',
          avgCost: '$23.30',
          lastPrice: '$29.10',
          dividendsCollected: '$0.00',
          return: '24.89%',
          total: '$103,305.000'
        },
        {
          country: "Spain",
          securityType: "Equity",
          industry: "Bank",
          investCategory: "Growth",
          company: "Banco de sabadell S.A",
          stockTicket: 'IBM',
          shares: '1000000',
          avgCost: '$1.23',
          lastPrice: '$1.32',
          dividendsCollected: '$6,000.00',
          return: '12.20%',
          total: '$138,000.000'
        },
        {
          country: "US",
          securityType: "Equity",
          industry: "Industrial",
          investCategory: "Dividend",
          company: "Arcosa Inc",
          stockTicket: 'ACA',
          shares: '4500',
          avgCost: '$58.01',
          lastPrice: '$83.51',
          dividendsCollected: '$900.00',
          return: '44.30%',
          total: '$376,695.000'
        },
        {
          country: "Spain",
          securityType: "Equity",
          industry: "Energy",
          investCategory: "Growth",
          company: "Fluidra S.A",
          stockTicket: 'FDR.MC',
          shares: '12000',
          avgCost: '$14.94',
          lastPrice: '$19.56',
          dividendsCollected: '$0.00',
          return: '30.92%',
          total: '$234,720.000'
        },
        {
          country: "Spain",
          securityType: "Equity",
          industry: "Energy",
          investCategory: "Growth",
          company: "Compania de Disstribucion Integral Logistica Holdings",
          stockTicket: 'LOG.MC',
          shares: '11000',
          avgCost: '$22.76',
          lastPrice: '$24.20',
          dividendsCollected: '$21,780.00',
          return: '15.03%',
          total: '$287,980.000'
        },
        {
          country: "",
          securityType: "",
          industry: "",
          investCategory: "",
          company: "",
          stockTicket: '',
          shares: '',
          avgCost: '',
          lastPrice: '',
          dividendsCollected: '',
          return: 'Net Asset Value of Quantum Capital',
          total: '$3,457,099.00'
        },
      ],
    },
    {
      percentage: 36.2,
      year: 2022,
      thisYear: false,
      tableHeaders: [
        "Country",
        "Security Type",
        "Industry",
        "Invest Category",
        "Company",
        "Stock ticket",
        "Shares",
        "Avg Cost",
        "Last Price",
        "Dividends Collected",
        "Return",
        "Total Gain/Loss"
      ],
      tableRows: [
        {
          country: "Argentina",
          securityType: "Equity",
          industry: "Retail",
          investCategory: "Growth",
          company: "Mercado Libre",
          stockTicket: 'MELI',
          shares: '200',
          avgCost: '$1,325.00',
          lastPrice: '$1.348',
          dividendsCollected: '$0.00',
          return: '1.74%',
          total: '$296,600.000'
        },
        {
          country: "Spain",
          securityType: "Equity",
          industry: "Energy",
          investCategory: "Value",
          company: "Iberdrola",
          stockTicket: 'IBE',
          shares: '28600',
          avgCost: '$8.73',
          lastPrice: '$10.08',
          dividendsCollected: '$14,872.00',
          return: '21.42%',
          total: '$303,160.000'
        },
        {
          country: "US",
          securityType: "Equity",
          industry: "Fund",
          investCategory: "Value",
          company: "Berkshire Hathway",
          stockTicket: 'BRKB',
          shares: '650',
          avgCost: '$230.00',
          lastPrice: '$1.348',
          dividendsCollected: '$0.00',
          return: '38.65%',
          total: '$207,285.000'
        },
        {
          country: "Argentina",
          securityType: "Equity",
          industry: "Bank",
          investCategory: "Growth",
          company: "Grupo Financiero Galicia",
          stockTicket: 'GGAL',
          shares: '24000',
          avgCost: '$8.20',
          lastPrice: '$10.40',
          dividendsCollected: '$5,040.00',
          return: '37.93%',
          total: '$271,440.000'
        },
        {
          country: "Brazil",
          securityType: "Equity",
          industry: "Oil & Gas",
          investCategory: "Dividend",
          company: "Petrolero Brasilero SA",
          stockTicket: 'PBR',
          shares: '10000',
          avgCost: '$10.95',
          lastPrice: '$27.52',
          dividendsCollected: '$33,100.00',
          return: '76.80%',
          total: '$193,600.000'
        },
        {
          country: "Argentina",
          securityType: "Equity",
          industry: "Oil & Gas",
          investCategory: "Growth",
          company: "YPF Sociedad S.A",
          stockTicket: 'YPF',
          shares: '25000',
          avgCost: '$3.82',
          lastPrice: '$3.76',
          dividendsCollected: '$0.00',
          return: '137.96%',
          total: '$227,250.000'
        },
        {
          country: "Argentina",
          securityType: "Equity",
          industry: "Oil & Gas",
          investCategory: "Growth",
          company: "Pampa Energia SA",
          stockTicket: 'PAM',
          shares: '6000',
          avgCost: '$20.31',
          lastPrice: '$32.08',
          dividendsCollected: '$0.00',
          return: '47.46%',
          total: '$179,700.000'
        },
        {
          country: "Spain",
          securityType: "Equity",
          industry: "Construction Materials",
          investCategory: "Dividend",
          company: "Gerdau SA",
          stockTicket: 'GGB',
          shares: '14000',
          avgCost: '$5.90',
          lastPrice: '$27.91',
          dividendsCollected: '$9,380.00',
          return: '13.39%',
          total: '$93,660.000'
        },
        {
          country: "Peru",
          securityType: "Equity",
          industry: "Bank",
          investCategory: "Dividend",
          company: "Credicorp Ltd",
          stockTicket: 'BAP',
          shares: '1400',
          avgCost: '$124.91',
          lastPrice: '$5.56',
          dividendsCollected: '$9,128.00',
          return: '30.89%',
          total: '$228,900.000'
        },
        {
          country: "US",
          securityType: "Equity",
          industry: "Tech",
          investCategory: "Dividend",
          company: "International Business Machines",
          stockTicket: 'IBM',
          shares: '12000',
          avgCost: '$8.15',
          lastPrice: '$163.04',
          dividendsCollected: '$79,080.00',
          return: '113.37%',
          total: '$208,680.000'
        },
        {
          country: "Brazil",
          securityType: "Equity",
          industry: "Paper and Forest Products",
          investCategory: "Value",
          company: "SZ",
          stockTicket: 'n/a',
          shares: '12000',
          avgCost: '$8.61',
          lastPrice: 'n/a',
          dividendsCollected: '$0.00',
          return: '19.86%',
          total: '$123,840.000'
        },
        {
          country: "US",
          securityType: "Equity",
          industry: "Healthcare",
          investCategory: "Value",
          company: "Johnson & Johnson",
          stockTicket: 'JNJ',
          shares: '400',
          avgCost: '$174.84',
          lastPrice: '$27.91',
          dividendsCollected: '$1,780.00',
          return: '3.96%',
          total: '$72,708.000'
        },
        {
          country: "US",
          securityType: "Equity",
          industry: "Financial Services",
          investCategory: "Value",
          company: "Intercorp Financial Services",
          stockTicket: 'IFS',
          shares: '1500',
          avgCost: '$22.01',
          lastPrice: '$5.56',
          dividendsCollected: '$0.00',
          return: '4.41%',
          total: '$34,470.000'
        },
        {
          country: "US",
          securityType: "Equity",
          industry: "n/a",
          investCategory: "Dividend",
          company: "Cash and treasuries",
          stockTicket: 'n/a',
          shares: 'n/a',
          avgCost: 'n/a',
          lastPrice: '$163.04',
          dividendsCollected: 'n/a',
          return: '0.00%',
          total: '$115,897.000'
        },
        {
          country: "",
          securityType: "",
          industry: "",
          investCategory: "",
          company: "",
          stockTicket: '',
          shares: '',
          avgCost: '',
          lastPrice: '',
          dividendsCollected: '',
          return: 'Net Asset Value of Quantum Capital',
          total: '$2,682,660.00'
        },
      ],
    },
    {
      percentage: 17.6,
      year: 2021,
      thisYear: false,
      tableHeaders: [
        "Country",
        "Security Type",
        "Industry",
        "Invest Category",
        "Company",
        "Stock ticket",
        "Shares",
        "Avg Cost",
        "Last Price",
        "Dividends Collected",
        "Return",
        "Total Gain/Loss"
      ],
      tableRows: [
        {
          country: "Argentina",
          securityType: "Equity",
          industry: "Retail",
          investCategory: "Growth",
          company: "Mercado Libre",
          stockTicket: 'MELI',
          shares: '500',
          avgCost: '$1,300.00',
          lastPrice: '$1.348',
          dividendsCollected: '$0.00',
          return: '3.69%',
          total: '$674,000.000'
        },
        {
          country: "Spain",
          securityType: "Equity",
          industry: "Energy",
          investCategory: "Value",
          company: "Iberdrola",
          stockTicket: 'IBE',
          shares: '16500',
          avgCost: '$8.73',
          lastPrice: '$10.08',
          dividendsCollected: '$8,745',
          return: '21.53%',
          total: '$175,065.000'
        },
        {
          country: "US",
          securityType: "Equity",
          industry: "Fund",
          investCategory: "Value",
          company: "Berkshire Hathway",
          stockTicket: 'BRKB',
          shares: '550',
          avgCost: '$273.40',
          lastPrice: '$1.348',
          dividendsCollected: '$0.00',
          return: '18.87%',
          total: '$150,370.000'
        },
        {
          country: "Argentina",
          securityType: "Equity",
          industry: "Bank",
          investCategory: "Growth",
          company: "Grupo Financiero Galicia",
          stockTicket: 'GGAL',
          shares: '16000',
          avgCost: '$8.20',
          lastPrice: '$10.40',
          dividendsCollected: '$1,280.00',
          return: '27.80%',
          total: '$167,680.000'
        },
        {
          country: "Spain",
          securityType: "Equity",
          industry: "Energy",
          investCategory: "Value",
          company: "Acciona Energías Renovables",
          stockTicket: 'ANE',
          shares: '1700',
          avgCost: '$29.39',
          lastPrice: '$27.52',
          dividendsCollected: '$561.00',
          return: '-5.24%',
          total: '$47,345.000'
        },
        {
          country: "Brazil",
          securityType: "Equity",
          industry: "Oil & Gas",
          investCategory: "Value",
          company: "Ultrapar Participaçōes",
          stockTicket: 'UGP',
          shares: '20000',
          avgCost: '$3.41',
          lastPrice: '$3.76',
          dividendsCollected: '$1,400.00',
          return: '12.32%',
          total: '$76,600.000'
        },
        {
          country: "Netherlands",
          securityType: "Equity",
          industry: "Industrial",
          investCategory: "Value",
          company: "ArcelorMittal",
          stockTicket: 'MT',
          shares: '3000',
          avgCost: '$22.90',
          lastPrice: '$32.08',
          dividendsCollected: '$1,140.00',
          return: '41.75%',
          total: '$97,380.000'
        },
        {
          country: "US",
          securityType: "Equity",
          industry: "Bank",
          investCategory: "Value",
          company: "Intercorp Financial Services",
          stockTicket: 'IFS',
          shares: '1500',
          avgCost: '$22.07',
          lastPrice: '$27.91',
          dividendsCollected: '$2,700.00',
          return: '34.62%',
          total: '$44,565.000'
        },
        {
          country: "Brazil",
          securityType: "Equity",
          industry: "Bank",
          investCategory: "Value",
          company: "Itau Unibanco Holdings SA",
          stockTicket: 'ITUB',
          shares: '1200',
          avgCost: '$4.45',
          lastPrice: '$5.56',
          dividendsCollected: '$1,440.00',
          return: '27.64%',
          total: '$68,160.000'
        },
        {
          country: "US",
          securityType: "Equity",
          industry: "Bank",
          investCategory: "Value",
          company: "JP Morgan Chase & CO",
          stockTicket: 'JPM',
          shares: '725',
          avgCost: '$137.00',
          lastPrice: '$163.04',
          dividendsCollected: '$2,755.00',
          return: '21.17%',
          total: '$120,959.000'
        },
        {
          country: "US",
          securityType: "Equity",
          industry: "n/a",
          investCategory: "Dividend",
          company: "Cash and Treasuries",
          stockTicket: 'n/a',
          shares: 'n/a',
          avgCost: 'n/a',
          lastPrice: 'n/a',
          dividendsCollected: 'n/a',
          return: '0.00%',
          total: '$100,000.000'
        },
        {
          country: "",
          securityType: "",
          industry: "",
          investCategory: "",
          company: "",
          stockTicket: '',
          shares: '',
          avgCost: '',
          lastPrice: '',
          dividendsCollected: '',
          return: 'Net Asset Value of Quantum Capital',
          total: '$1,742,145.00'
        },
      
      ],
    },
  ];